### ISSUE TITLE
Problems installing Kaldi

### ISSUE THREAD

**Issue by jdcai** [dictation-toolbox/Caster#772]
**Describe the bug**
When going through the steps in https://caster.readthedocs.io/en/latest/readthedocs/Installation/Kaldi/ I encounter some errors and can't get Caster/Kaldi to run.

**Steps to reproduce**
Following the instructions on https://caster.readthedocs.io/en/latest/readthedocs/Installation/Kaldi/
Running `Install_Caster_Kaldi.bat` it gives `ERROR: unknown command "dragonfly2[kaldi]"`.
Inside `Install_Caster_Kaldi.bat` it's missing `install`.

After adding that and running it again I got an error related to webrtcvad. I had to run `pip install https://github.com/daanzu/kaldi-active-grammar/releases/download/v0.4.0/webrtcvad-2.0.10-cp27-cp27m-win_amd64.whl` which I found on https://dragonfly2.readthedocs.io/en/latest/kaldi_engine.html. 

After that all my requirements are satisfied when I run `Install_Caster_Kaldi.bat`.
I then added the model folder and ran `Run_Caster_Kaldi.bat` which gave me this error

Runnig Kaldi from Dragonfly CLI
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 163, in _run_module_as_main mod_name, _Error)
  File "C:\Python27\lib\runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "C:\Python27\lib\site-packages\dragonfly\__init__.py", line 32, in <module>
    from .grammar.grammar_connection import ConnectionGrammar
  File "C:\Python27\lib\site-packages\dragonfly\grammar\grammar_connection.py", line 35, in <module>
    raise error
ImportError: DLL load failed: %1 is not a valid Win32 application.
'model_dir' is not recognized as an internal or external command,
operable program or batch file.
'vad_padding_end_ms' is not recognized as an internal or external command,
operable program or batch file.

**System:**
 - OS: Windows 10
 - Version: master branch

**Comment by LexiconCode** [comment]
Thank you for reporting this! I fixed the install issue in https://github.com/dictation-toolbox/Caster/commit/eb1966dee5414b1e4d8c768d801f993f924542cc and simplified the https://github.com/dictation-toolbox/Caster/commit/ad10caf6f07e4b594ec5da3b69fac64c1a19967a kaldi arguments. However I would recommend for the moment downloading the dragonfly master branch. [Here](https://github.com/dictation-toolbox/dragonfly/archive/master.zip)

Even though it's unreleased there are two reasons for this recommendation.
- Dependency change `webrtcvad-2.0.10-cp27-cp27m-win_amd64.whl` to `webrtcvad-wheels` 
The wheels is on PyPi, works for Python 2/3, and does not require a compiler
- Dependency change to `pyaudio` to `sounddevice`, does not require compiler and is a less complex package.

1. Download and Unzip to preferred file location.
2. Navigating through command prompt to the extracted folder.
3. `python -m pip install -e .[kaldi]` (this will uninstall current dragonfly and reinstall with the version found in the file)

Note don't delete the Dragonfly file is that is the install location rather than the site package in Python. Once Dragonfly has its next release it can be installed by the normal method.

**Comment by jdcai** [comment]
I went through the steps and used the master branch. Install seemed to go fine but when I run `Run_Caster_Kaldi.bat` I get the same error as before just without the not recognized command.

**Comment by LexiconCode** [comment]
I changed some of the launch flags in the master branch of Caster as well for kaldi. Delete and redownload the master Caster branch if you're not using git pull.

**Comment by jdcai** [comment]
Yup I'm on the most recent Caster master branch. I still get the error. Also happens when I run `Run_Caster_WSR.bat`.

Runnig Kaldi from Dragonfly CLI
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "C:\Python27\lib\runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "C:\Python27\lib\site-packages\dragonfly\__init__.py", line 32, in <module>
    from .grammar.grammar_connection import ConnectionGrammar
  File "C:\Python27\lib\site-packages\dragonfly\grammar\grammar_connection.py", line 35, in <module>
    raise error
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by LexiconCode** [comment]
I will follow up with Dragonfly.

**Comment by LexiconCode** [comment]
Looks like it's an issue with 'pywin32'. Try reinstalling with pip.

Alternatively you could try using the windows installer 

https://github.com/mhammond/pywin32/releases/download/b227/pywin32-227.win-amd64-py2.7.exe

**Comment by jdcai** [comment]
Okay I installed using the windows installer and now I get this

Runnig Kaldi from Dragonfly CLI
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "C:\Python27\lib\runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "C:\Python27\lib\site-packages\dragonfly\__init__.py", line 81, in <module>
    from .accessibility     import (CursorPosition, TextQuery,
  File "C:\Python27\lib\site-packages\dragonfly\accessibility\__init__.py", line 4, in <module>
    from . import controller
  File "C:\Python27\lib\site-packages\dragonfly\accessibility\controller.py", line 10, in <module>
    from . import utils
  File "C:\Python27\lib\site-packages\dragonfly\accessibility\utils.py", line 9, in <module>
    import regex
  File "C:\Python27\lib\site-packages\regex\__init__.py", line 1, in <module>
    from .regex import *
  File "C:\Python27\lib\site-packages\regex\regex.py", line 391, in <module>
    import _regex_core
  File "C:\Python27\lib\site-packages\regex\_regex_core.py", line 21, in <module>
    import _regex
ImportError: DLL load failed: %1 is not a valid Win32 application.
Press any key to continue . . .

**Comment by jdcai** [comment]
Okay I managed to get it working. I uninstalled python and deleted everything in python27 folder then reinstalled python, installed pywin32 with installer, installed dragonfly master and ran `install_caster_kaldi.bat` then ran `Run_Caster_Kaldi.bat` and it worked. Though now I'm having issues with the commands.

Some commands don't seem to work anymore or only work in odd ways. 
Some of the ones I found so far
`switch window` sometimes works or sometimes does nothing
in chrome
`go back` doesn't work unless you say `go back n` where n is a number greater than 1. It will do the command n-1 times. Ex: If you say `go back 2` it will go back 1.
Same thing happens with others that use n like `go forward n`, `back tab n`, `next tab n`
also happens with `shock` which doesn't work unless you say `shock 2`.

Seems like commands that use a function still work like `kick`, or commands that have %(n)s like `latch`'s `R(Key("home:%(nnavi10)s"))`. Commands with `* Repeat(extra="n")` work if you say 2 or higher.
If its just a simple one like `R(Key("t")` then it doesn't seem to do anything. 

Should I open a new issue for this since its not about installation anymore?

**Comment by LexiconCode** [comment]
Excellent!

Go ahead and open up a new issue. I will look into this, but I won't be able to do testing until late tomorrow as I have another overnight shift coming up. 

I will repost what's below in the new issue. For now there may be a few things to keep in mind which I will keep adding too as I have time. Some of this information will turn into documentation as well.

- There is an ongoing bug semi-related at least with dictation [here](https://github.com/dictation-toolbox/dragonfly/issues/217)

- Kaldi performs better when grammars are less ambiguous. So you may need customize as needed based on your experience with certain commands.

- Utilize some grammar debugging tools `python -m dragonfly test _caster.py` this takes the speech recognition out of the stack. Allows you to type words as if it spoken recognition. Lowercase words emulates commands, uppercase words act as free dictation which can be combined. 
	- For example typeing `gerrish snake VARIABLE NAME` then `variable_Name` should type out after pressing enter.
	- You can utilize --delay <n> flag with <n> being the delay before the command is executed so you can switch the context needed. There are a few other options. https://dragonfly2.readthedocs.io/en/latest/cli.html#test-exampleshttps://dragonfly2.readthedocs.io/en/latest/cli.html#test-examples

- You can load any dragonfly rule via command line. For example `sample.py` as a vanilla dragonfly rule. `python -m dragonfly load sample.py --engine kaldi --no-recobs-messages`
	- May be useful for creating a test case that we can submit back to daanzu if we find issues with kaldi that is reproducible.
